"""empty message

Revision ID: 0ea69329266d
Revises: 184fd826a671
Create Date: 2020-11-04 11:33:22.110993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ea69329266d'
down_revision = '184fd826a671'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('turnos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=40), nullable=True),
    sa.Column('dia', sa.Date(), nullable=True),
    sa.Column('hora', sa.Time(), nullable=True),
    sa.Column('centro_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['centro_id'], ['centros.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('turnos')
    # ### end Alembic commands ###
