"""empty message

Revision ID: 3640ebd4225c
Revises: f8fb2d7e5058
Create Date: 2020-10-21 14:02:35.509534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3640ebd4225c'
down_revision = 'f8fb2d7e5058'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('centros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=40), nullable=True),
    sa.Column('direccion', sa.String(length=40), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('apertura', sa.Time(), nullable=True),
    sa.Column('cierre', sa.Time(), nullable=True),
    sa.Column('tipo', sa.String(length=30), nullable=True),
    sa.Column('municipio', sa.String(length=30), nullable=True),
    sa.Column('web', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=40), nullable=True),
    sa.Column('coordenadas', sa.String(length=40), nullable=True),
    sa.Column('estado', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('centros')
    # ### end Alembic commands ###
