"""empty message

Revision ID: 3e92da5eb4b9
Revises: 9395857b9e7c
Create Date: 2020-10-25 20:38:11.341023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e92da5eb4b9'
down_revision = '9395857b9e7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipocentros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('centros', sa.Column('tipocentro_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'centros', 'tipocentros', ['tipocentro_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'centros', type_='foreignkey')
    op.drop_column('centros', 'tipocentro_id')
    op.drop_table('tipocentros')
    # ### end Alembic commands ###
