"""empty message

Revision ID: 6a2671375d82
Revises: 0c8c1bf061ac
Create Date: 2020-10-08 13:37:59.155221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a2671375d82'
down_revision = '0c8c1bf061ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuraciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=20), nullable=True),
    sa.Column('descripcion', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=20), nullable=True),
    sa.Column('cantPaginacion', sa.Integer(), nullable=True),
    sa.Column('estadoSitio', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('configuraciones')
    # ### end Alembic commands ###
