"""empty message

Revision ID: a61dbd85b472
Revises: 3640ebd4225c
Create Date: 2020-10-22 14:02:55.126935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a61dbd85b472'
down_revision = '3640ebd4225c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_centros_email'), 'centros', ['email'], unique=True)
    op.create_index(op.f('ix_centros_nombre'), 'centros', ['nombre'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_centros_nombre'), table_name='centros')
    op.drop_index(op.f('ix_centros_email'), table_name='centros')
    # ### end Alembic commands ###
