"""empty message

Revision ID: dead2de1da37
Revises: 3e92da5eb4b9
Create Date: 2020-10-25 22:09:15.798819

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dead2de1da37'
down_revision = '3e92da5eb4b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('centros', sa.Column('tipo_id', sa.Integer(), nullable=True))
    op.drop_constraint('centros_ibfk_1', 'centros', type_='foreignkey')
    op.create_foreign_key(None, 'centros', 'tipocentros', ['tipo_id'], ['id'])
    op.drop_column('centros', 'tipocentro_id')
    op.drop_column('centros', 'tipo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('centros', sa.Column('tipo', mysql.VARCHAR(collation='latin1_spanish_ci', length=30), nullable=True))
    op.add_column('centros', sa.Column('tipocentro_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'centros', type_='foreignkey')
    op.create_foreign_key('centros_ibfk_1', 'centros', 'tipocentros', ['tipocentro_id'], ['id'])
    op.drop_column('centros', 'tipo_id')
    # ### end Alembic commands ###
