"""empty message

Revision ID: eb0f0004d73d
Revises: dead2de1da37
Create Date: 2020-10-30 20:05:51.016336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb0f0004d73d'
down_revision = 'dead2de1da37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('turnos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=40), nullable=True),
    sa.Column('turno', sa.DateTime(), nullable=True),
    sa.Column('centro_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['centro_id'], ['centros.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('turnos')
    # ### end Alembic commands ###
